version: '3.1'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
